version: "3"

services:

  backend_app:
    container_name: backend_app
    image: php:7.2-apache
    volumes: 
      - $PWD/admin:/var/www/html
    ports: 
      - 8000:80

  websocket:
    container_name: websocket
    build:
      context: ./websocket
      dockerfile: Dockerfile
    image: websocket
    volumes: 
      - $PWD/websocket:/websocket
    depends_on:
       - backend_app